services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: pesquisa_satisfacao
    ports:
      - "9307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    restart: unless-stopped
    networks:
      - api
  
  api:
    build: ./pesquisa_satisfacao
    container_name: pesquisa_satisfacao
    depends_on:
      - db
    restart: unless-stopped
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/pesquisa_satisfacao
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 123456
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "90902:8081"
    networks:
      - api

  nginx:
    build: ./nginx
    ports:
      - "80802:82"
    volumes:
      - ./html:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - api
    networks:
      - api

networks:
  api:
    driver: bridge

volumes:
  db_data: