services:
  db:
    image: mysql:8.0
    container_name: mysql_pesquisa
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: pesquisa_satisfacao
    ports:
      - "9307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    restart: unless-stopped
    networks:
      - api
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "root",
          "-p123456",
        ]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 10s
  
  api:
    build: ./pesquisa_satisfacao
    container_name: pesquisa_satisfacao
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/pesquisa_satisfacao
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 123456
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "59092:8081"
    networks:
      - api

  nginx:
    build: ./nginx
    ports:
      - "58082:82"
    volumes:
      - ./html:/usr/share/nginx/html:ro
    depends_on:
      - api
    networks:
      - api

networks:
  api:
    driver: bridge

volumes:
  db_data: