name: Deploy Podman Compose

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Deploy via Podman Compose
        run: |
          podman-compose down -v
          podman-compose up -d --build
